# Generated by Django 3.1.2 on 2020-10-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('carousel_id', models.AutoField(primary_key=True, serialize=False)),
                ('carousel_name', models.CharField(default='', max_length=200)),
                ('carousel_category', models.CharField(choices=[('Brigadeiro', 'Brigadeiro'), ('Brownie', 'Brownie'), ('Cake', 'Cake'), ('Cheesecake', 'Cheesecake'), ("Chef's Special", "Chef's Special"), ('Cupcake', 'Cupcake'), ('Fudge', 'Fudge'), ('Tea Time', 'Tea Time')], max_length=110)),
                ('carousel_image', models.ImageField(default='', upload_to='home/images')),
            ],
        ),
    ]
