# Generated by Django 3.1.2 on 2020-10-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='carousel_image',
            field=models.ImageField(default='', upload_to='catalogue/images'),
        ),
    ]
