# Generated by Django 3.1.2 on 2020-10-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20201006_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselslide',
            name='carousel_bitrix_link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
