# Generated by Django 3.1.2 on 2020-10-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_carouselslide_carousel_bitrix_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselslide',
            old_name='carousel_bitrix_link',
            new_name='image_link',
        ),
    ]
