# Generated by Django 3.1.2 on 2020-10-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20201009_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselslide',
            name='carousel_image',
        ),
    ]
