# Generated by Django 3.1.2 on 2020-10-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarouselSlides',
            new_name='CarouselSlide',
        ),
    ]
