# Generated by Django 3.1.2 on 2020-10-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201005_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselslide',
            name='cloudinary_link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
