# Generated by Django 3.1.2 on 2020-10-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_carouselslide_cloudinary_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselslide',
            name='cloudinary_link',
        ),
    ]
