# Generated by Django 3.1.2 on 2020-10-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_carouselslide_cloudinary_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselSlide',
        ),
    ]
