# Generated by Django 3.1.2 on 2020-10-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=300)),
                ('product_category', models.CharField(choices=[('Brigadeiro', 'Brigadeiro'), ('Brownie', 'Brownie'), ('Cake', 'Cake'), ('Cheesecake', 'Cheesecake'), ("Chef's Special", "Chef's Special"), ('Cupcakes', 'Cupcakes'), ('Fudges', 'Fudges'), ('Tea Time', 'Tea Time')], default='', max_length=110)),
                ('product_preview_image', models.ImageField(default='', upload_to='menu/images')),
                ('product_price', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
