# Generated by Django 3.1.2 on 2020-10-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(default='', max_length=300)),
                ('productCategory', models.CharField(choices=[('A', 'Brigadeiro'), ('B', 'Brownie'), ('C', 'Cake'), ('D', 'Cheesecake'), ('E', "Chef's Special"), ('F', 'Cupcakes'), ('G', 'Fudges'), ('H', 'Tea Time')], max_length=300)),
            ],
        ),
    ]
