# Generated by Django 3.1.2 on 2020-10-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Brigadeiro', 'Brigadeiro'), ('Brownie', 'Brownie'), ('Cake', 'Cake'), ('Cheesecake', 'Cheesecake'), ("Chef's Special", "Chef's Special"), ('Cupcakes', 'Cupcakes'), ('Fudges', 'Fudges'), ('Tea Time', 'Tea Time')], max_length=110),
        ),
    ]
