# Generated by Django 3.1.2 on 2020-10-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productCategory',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='product_name',
        ),
    ]
