# Generated by Django 3.1.2 on 2020-10-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20201005_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Brigadeiro', 'Brigadeiro'), ('Brownie', 'Brownie'), ('Cake', 'Cake'), ('Cheesecake', 'Cheesecake'), ("Chef's Special", "Chef's Special"), ('Cupcake', 'Cupcake'), ('Fudge', 'Fudge'), ('Tea Time', 'Tea Time')], max_length=110),
        ),
    ]
