# Generated by Django 3.1.2 on 2020-10-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20201005_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_link',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
