# Generated by Django 3.1.2 on 2020-10-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_product_product_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_preview_image',
        ),
    ]
